### ISSUE TITLE
Running a given test file

### ISSUE THREAD

**Issue by scls19fr** [ianfixes/arduino_ci#81] opened 2019-01-13 19:13 UTC
Hello,

I'm trying to use arduino_ci for test driven development.

Unfortunately I haven't seen a way to run a given test file.

I was expecting to run (only) one test file using for example:

    bundle exec arduino_ci_remote.rb test/test_application.cpp

or just one unit test

    bundle exec arduino_ci_remote.rb test/test_application.cpp::unittest_name

(it may be harder)

But being at least a test file could speedup development process.

Kind regards

**Comment by ianfixes** [comment] 2019-01-14 11:43
Duplicate of #48

**Closed by ianfixes** 2019-01-14 11:43 UTC
Labels: duplicate, question

**Comment by ianfixes** [comment] 2019-01-30 14:46
I've pushed updates to REFERENCE.md, hopefully they will explain how to accomplish most of this.
